name: Assignment

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: python -m unittest discover -s tests -v

      - name: get python version
        run: python --version

  build:
    needs: ["ci"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    env:
      IMAGE_NAME: tiny-health-app
      IMAGE_TAR: tiny-health-app.tar
      ARTIFACT_NAME: tiny-health-app-image
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set image tag
        id: image-tag
        run: |
          IMAGE_TAG="run-${GITHUB_RUN_NUMBER}"
          echo "image_tag=$IMAGE_TAG-${{ matrix.python-version }}" >> "$GITHUB_OUTPUT"

      - name: Build docker with action
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.image_tag }}
          outputs: type=docker,dest=${{ matrix.python-version }}-${{ env.IMAGE_TAR }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.python-version }}-${{ env.ARTIFACT_NAME }}
          path: ${{ matrix.python-version }}-${{ env.IMAGE_TAR }}
          retention-days: 7
